<?php

namespace Citrus\DHFi;

$citrus_dhfi_default_option = array(
	OPTION_API_KEY => "",
	OPTION_STORE_ID => "",
	OPTION_ENABLE_LOG => OPTION_ENABLE_LOG_DEFUALT,
	OPTION_API_ENDPOINT => OPTION_API_ENDPOINT_DEFAULT,
	OPTION_PAYMENT_URL_TEMPLATE => OPTION_PAYMENT_URL_TEMPLATE_DEFAULT,
);
