CREATE TABLE `citrus_dhfi_payments`
(
    ID             INT(11) NOT NULL,
    DATE_UPDATE    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DATE_CREATE    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ACCOUNT_NUMBER VARCHAR(255) NOT NULL,
    PAYSYSTEM_ID   INT(11) DEFAULT NULL,
    REGISTRY       VARCHAR(255) NOT NULL,
    AMOUNT         DECIMAL(12, 2) NOT NULL,
    STATUS         VARCHAR(32) DEFAULT 'Not_paid',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_ID` (`ID`),
    KEY `IX_ENTITY_ID` (`ACCOUNT_NUMBER`)
);